name: Rust

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release --package hikka_cli --bin hikka_cli --target-dir ./build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hikka_cli
        path: build/**/hikka_cli
